FROM node:14.16.0-alpine

WORKDIR /home/node/grenache-grape

RUN apk add --no-cache --virtual \
  .gyp \
  python3 \
  make \
  g++ \
  git \
  openssh \
  bash

RUN git clone https://github.com/bitfinexcom/grenache-grape.git . \
  && npm i --production --no-audit

COPY ./scripts/grenache-grape-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["grenache-grape-entrypoint.sh"]
CMD ["bin/grape.js"]
