FROM node:14.16.0-alpine

WORKDIR /home/node/bfx-reports-framework

RUN apk add --no-cache --virtual \
  .gyp \
  python3 \
  make \
  g++ \
  git \
  openssh \
  bash

COPY . .

RUN ./scripts/init-worker.sh

COPY ./scripts/worker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["worker-entrypoint.sh"]
CMD ["bin/grape.js"]
