'use strict'

module.exports = {
  INITIAL_PROGRESS: 'SYNCHRONIZATION_HAS_NOT_BEEN_STARTED_YET', // Sets on an app launch
  ACITVE_PROGRESS: 'SYNCHRONIZATION_IS_STARTED', // When sync is in progress
  FINISHED_PROGRESS: 'SYNCHRONIZATION_IS_FINISHED', // When sync is finished
  INTERRUPTED_PROGRESS: 'SYNCHRONIZATION_HAS_BEEN_INTERRUPTED' // When interrupted
}
