'use strict'

module.exports = {
  INITIAL_PROGRESS: 'SYNCHRONIZATION_HAS_NOT_STARTED_YET',
  ACITVE_PROGRESS: 'SYNCHRONIZATION_IS_STARTED',
  INTERRUPTED_PROGRESS: 'SYNCHRONIZATION_HAS_BEEN_INTERRUPTED'
}
