'use strict'

module.exports = {
  USERS: 'users',
  LEDGERS: 'ledgers',
  TRADES: 'trades',
  FUNDING_TRADES: 'fundingTrades',
  PUBLIC_TRADES: 'publicTrades',
  ORDERS: 'orders',
  MOVEMENTS: 'movements',
  FUNDING_OFFER_HISTORY: 'fundingOfferHistory',
  FUNDING_LOAN_HISTORY: 'fundingLoanHistory',
  FUNDING_CREDIT_HISTORY: 'fundingCreditHistory',
  TICKERS_HISTORY: 'tickersHistory',
  POSITIONS_HISTORY: 'positionsHistory',
  SYMBOLS: 'symbols',
  INACTIVE_SYMBOLS: 'inactiveSymbols',
  FUTURES: 'futures',
  CURRENCIES: 'currencies',
  CANDLES: 'candles',
  STATUS_MESSAGES: 'statusMessages',
  PUBLIC_COLLS_CONF: 'publicСollsСonf',
  SCHEDULER: 'scheduler',
  SYNC_MODE: 'syncMode',
  PROGRESS: 'progress',
  SYNC_QUEUE: 'syncQueue',
  LOGINS: 'logins',
  CHANGE_LOGS: 'changeLogs',
  SUB_ACCOUNTS: 'subAccounts'
}
