'use strict'

const TYPES = require('bfx-report/workers/loc.api/di/types')

module.exports = {
  ...TYPES,
  TABLES_NAMES: Symbol.for('TABLES_NAMES'),
  ALLOWED_COLLS: Symbol.for('ALLOWED_COLLS'),
  FrameworkRServiceDepsSchema: Symbol.for('FrameworkRServiceDepsSchema'),
  GRC_BFX_OPTS: Symbol.for('GRC_BFX_OPTS'),
  ApiMiddlewareHandlerAfter: Symbol.for('ApiMiddlewareHandlerAfter'),
  ApiMiddleware: Symbol.for('ApiMiddleware'),
  DataInserter: Symbol.for('DataInserter'),
  DataInserterFactory: Symbol.for('DataInserterFactory'),
  WSTransport: Symbol.for('WSTransport'),
  WSEventEmitter: Symbol.for('WSEventEmitter'),
  RedirectRequestsToApi: Symbol.for('RedirectRequestsToApi'),
  SyncSchema: Symbol.for('SyncSchema'),
  Sync: Symbol.for('Sync'),
  SyncQueue: Symbol.for('SyncQueue'),
  Progress: Symbol.for('Progress'),
  DB: Symbol.for('DB'),
  DAO: Symbol.for('DAO'),
  SqliteDAO: Symbol.for('SqliteDAO'),
  PublicСollsСonfAccessors: Symbol.for('PublicСollsСonfAccessors'),
  SearchClosePriceAndSumAmount: Symbol.for('SearchClosePriceAndSumAmount'),
  Wallets: Symbol.for('Wallets'),
  BalanceHistory: Symbol.for('BalanceHistory'),
  WinLoss: Symbol.for('WinLoss'),
  PositionsSnapshot: Symbol.for('PositionsSnapshot'),
  FullSnapshotReport: Symbol.for('FullSnapshotReport'),
  CurrencyConverter: Symbol.for('CurrencyConverter'),
  FullSnapshotReportCsvWriter: Symbol.for('FullSnapshotReportCsvWriter'),
  FOREX_SYMBS: Symbol.for('FOREX_SYMBS'),
  FullTaxReport: Symbol.for('FullTaxReport'),
  FullTaxReportCsvWriter: Symbol.for('FullTaxReportCsvWriter'),
  MigrationsFactory: Symbol.for('MigrationsFactory'),
  DbMigratorFactory: Symbol.for('DbMigratorFactory'),
  SqliteDbMigrator: Symbol.for('SqliteDbMigrator'),
  Trades: Symbol.for('Trades'),
  TradedVolume: Symbol.for('TradedVolume'),
  FeesReport: Symbol.for('FeesReport'),
  PerformingLoan: Symbol.for('PerformingLoan'),
  SubAccount: Symbol.for('SubAccount'),
  ConvertCurrencyHook: Symbol.for('ConvertCurrencyHook'),
  RecalcSubAccountLedgersBalancesHook: Symbol.for('RecalcSubAccountLedgersBalancesHook'),
  SubAccountApiData: Symbol.for('SubAccountApiData'),
  PositionsAudit: Symbol.for('PositionsAudit'),
  OrderTrades: Symbol.for('OrderTrades'),
  Crypto: Symbol.for('Crypto'),
  Authenticator: Symbol.for('Authenticator'),
  PrivResponder: Symbol.for('PrivResponder')
}
