'use strict'

const PROGRESS_STATES = {
  GENERATION_STARTED: 'GENERATION_STARTED',
  OBTAINING_CURRENCY_PRICES: 'OBTAINING_CURRENCY_PRICES',
  TRANSACTION_HISTORY_GENERATION: 'TRANSACTION_HISTORY_GENERATION',
  GENERATION_COMPLETED: 'GENERATION_COMPLETED',

  GENERATION_INTERRUPTED: 'GENERATION_INTERRUPTED'
}

module.exports = PROGRESS_STATES
