'use strict'

const TRX_TAX_TYPES = {
  AIRDROP_ON_WALLET: 'AIRDROP_ON_WALLET',
  MARGIN_FUNDING_PAYMENT: 'MARGIN_FUNDING_PAYMENT',
  AFFILIATE_REBATE: 'AFFILIATE_REBATE',
  STAKING_PAYMENT: 'STAKING_PAYMENT',

  EXCHANGE: 'EXCHANGE'
}

module.exports = TRX_TAX_TYPES
