'use strict'

const SEPARATOR = ':'

const PUBLIC = 'public'
const HIDDEN = 'hidden'

const UPDATABLE = 'updatable'
const INSERTABLE = 'insertable'

const ARRAY = 'array'
const OBJECT = 'object'
const ARRAY_OBJECTS = `${ARRAY}${SEPARATOR}${OBJECT}`

const INSERTABLE_ARRAY_OBJECTS = `${INSERTABLE}${SEPARATOR}${ARRAY_OBJECTS}`
const UPDATABLE_ARRAY_OBJECTS = `${UPDATABLE}${SEPARATOR}${ARRAY_OBJECTS}`
const UPDATABLE_ARRAY = `${UPDATABLE}${SEPARATOR}${ARRAY}`

const PUBLIC_INSERTABLE_ARRAY_OBJECTS = `${PUBLIC}${SEPARATOR}${INSERTABLE_ARRAY_OBJECTS}`
const PUBLIC_UPDATABLE_ARRAY_OBJECTS = `${PUBLIC}${SEPARATOR}${UPDATABLE_ARRAY_OBJECTS}`
const PUBLIC_UPDATABLE_ARRAY = `${PUBLIC}${SEPARATOR}${UPDATABLE_ARRAY}`

const HIDDEN_INSERTABLE_ARRAY_OBJECTS = `${HIDDEN}${SEPARATOR}${INSERTABLE_ARRAY_OBJECTS}`

module.exports = {
  SEPARATOR,

  PUBLIC,
  HIDDEN,

  UPDATABLE,
  INSERTABLE,

  ARRAY,
  OBJECT,
  ARRAY_OBJECTS,

  INSERTABLE_ARRAY_OBJECTS,
  UPDATABLE_ARRAY_OBJECTS,
  UPDATABLE_ARRAY,

  PUBLIC_INSERTABLE_ARRAY_OBJECTS,
  PUBLIC_UPDATABLE_ARRAY_OBJECTS,
  PUBLIC_UPDATABLE_ARRAY,

  HIDDEN_INSERTABLE_ARRAY_OBJECTS
}
