'use strict'

const LOCKED_JOB_STATE = 'LOCKED'
const NEW_JOB_STATE = 'NEW'
const FINISHED_JOB_STATE = 'FINISHED'
const ERROR_JOB_STATE = 'ERROR'

module.exports = {
  LOCKED_JOB_STATE,
  NEW_JOB_STATE,
  FINISHED_JOB_STATE,
  ERROR_JOB_STATE
}
