'use strict'

const ID_PRIMARY_KEY = 'INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT'

const BIGINT = 'BIGINT'
const BIGINT_NOT_NULL = `${BIGINT} NOT NULL`
const INTEGER = 'INT'
const INTEGER_NOT_NULL = `${INTEGER} NOT NULL`
const DECIMAL = 'DECIMAL(22,12)'
const DECIMAL_NOT_NULL = `${DECIMAL} NOT NULL`
const VARCHAR = 'VARCHAR(255)'
const VARCHAR_NOT_NULL = `${VARCHAR} NOT NULL`
const TEXT = 'TEXT'
const TEXT_NOT_NULL = `${TEXT} NOT NULL`

const DB_DATA_TYPES = {
  ID_PRIMARY_KEY,

  BIGINT,
  BIGINT_NOT_NULL,
  INTEGER,
  INTEGER_NOT_NULL,
  DECIMAL,
  DECIMAL_NOT_NULL,
  VARCHAR,
  VARCHAR_NOT_NULL,
  TEXT,
  TEXT_NOT_NULL
}

module.exports = DB_DATA_TYPES
